source 'http://rubygems.org'
ruby "2.2.3"
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'pg'
gem 'sinatra-cross_origin'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'rack-cors', :require => 'rack/cors'
gem 'bcrypt'
