development:
  adapter: postgresql
  encoding: unicode
  database: dronetournament
  pool: 10
  username: tcooper
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dronetournament
  pool: 50
  username: test
  password: test_password
