development:
  adapter: postgresql
  encoding: unicode
  database: dronetournament
  pool: 2
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dronetournament
  pool: 2
  username: test
  password: test_password
